let text = [
  'Rampo City',
  '',
  '■ Region Information',
  '  Region Name: Rampo City',
  '  Manager: rampotchi',
  '  Coordinates: -290 64 -410',
  '  Overview: A village with an application system featuring rich railways. No permission required is very nice.',
  '',
  '■ Basic Rules',
  '  • Entering Rampo City means agreeing to these regulations.',
  '  • PvP is allowed with mutual agreement as long as no damage is caused to surroundings.',
  '  • Destruction of others\' buildings is prohibited.',
  '  • Killing others\' animals is prohibited.',
  '  • Taking items from anything other than shared chests is prohibited.',
  '  • If you find dropped items, please return them to the owner.',
  '  • Please get permission before entering others\' homes.',
  '  • Follow the Minecraft server rules.',
  '',
  '■ Acceptance Policy',
  '  • People who have violated Discord or Minecraft server rules in the past may be refused.',
  '  • Violating regulations may result in expulsion from the village.',
  '',
  '■ Construction Guidelines',
  '  • Permission or notification may be required for construction within the village.',
  '  • Permission required for: special areas, near tracks/stations, filling rivers/seas, cutting mountains, building roads/railways, beacons/traps.',
  '  • Notification required for: building outside owned areas, underground/sky construction.',
  '',
  '■ Other Notes',
  '  • Free construction is allowed within owned areas.',
  '  • Small hills of a few blocks can be removed without permission.',
  '  • Relocation/removal orders may be issued for public facilities.',
  '  • Items that make server/world laggy are generally prohibited.',
  '  • Contact if you want owned land.',
  '',
  '■ Discord Thread',
  '  [link;https://discord.com/channels/888638910589206569/1220639447146692658;Rampo City Discussion]',
  '',
]

export default text; 