let text = [
  'mcscr.site',
  '',
  'A secondary and temporary website for ScJP Minecraft Server.',
  '',
  'ScJP Minecraft Server is a well-equipped server with comprehensive rules, where friendly and fun ScratchJP users gather! Newcomers are very welcome! 🎉🎉🎉',
  '',
  '■ Whitelist Application',
  '  To apply for whitelist, please visit [link;https://discord.com/channels/888638910589206569/1220479513071190077;Discord Channel]',
  '  Note: You must join the Scratch JP Discord server and complete Scratch authentication.',
  '',
  '■ Latest News & Announcements',
  '  • Recruitment information page opened! (2024/3/31)',
  '  • Please register facility information from "Facility Information"! (2024/3/28)',
  '  • Site published 🎉 (2024/3/27)',
  '',
  '■ Server Information Sections',
  '  • [link;/region;Region Information] - Information about regions in the server',
  '  • [link;/facility;Facility Information] - Information about facilities in the server',
  '  • [link;/railway;Railway Information] - Information about railways in the server',
  '  • [link;/recruitment;Recruitment Information] - Recruitment information in the server',
  '  • [link;/server;About Server] - Information about ScJP Minecraft Server',
  '',
  '',
  '',
  '■ THE REAL WEBSITE OF THE MINECRAFT SERVER I PROMISE IT\'S NOT A SCAM, BUT IT\'S WRITTEN IN JAPANESE so only japanese speakers can read it, ...right?',
  '  • [link;https://mcscr.jp;-> mcscr.jp]',
]

export default text; 