let text = [
  'Server Information',
  '',
  '■ Server Details',
  '  Server Owner: kouhei7497',
  '  Edition: Java (1.21.1), Bedrock (1.21.20)',
  '',
  '■ Server Rules',
  '  • Actions that cause trouble to others (explosions, griefing, etc.) are prohibited',
  '  • Keep item exchange rates reasonable',
  '  • Let\'s keep it peaceful',
  '  • Don\'t generate chunks excessively',
  '  • Using cheats will result in punishment',
  '  • Item trading without permission is considered theft and will be punished',
  '  • To prevent trouble, always leave text records for transactions',
  '  • Actions that put load on the server require owner confirmation',
  '  • Intentional PvP without mutual agreement is prohibited',
  '  • Each region can set their own PvP rules',
  '',
  '■ Important Notes',
  '  • Punishment content is determined at the discretion of the staff',
  '  • Users (MC server participants) are considered to agree to these rules',
  '  • Verbal agreements in VC are invalid - use text chat for records',
  '',
  '■ Server Map',
  '  Server map is available at [link;https://map.mcscr.jp;map.mcscr.jp]',
  '',
]

export default text;